export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const SEARCH_DATA_SUCCESS = "SEARCH_DATA_SUCCESS";
export const SEARCHED_KEYS = "SEARCHED_KEYS";
export const IS_SEARCH_ENABLED = "IS_SEARCH_ENABLED";
export const SEARCHED_WORD = "SEARCHED_WORD";
export const HIDE_SEARCH = "HIDE_SEARCH";
